str_tree_delete = 'Дерево "{}" и его содержиоме удалено'
str_tree_input = 'Дерево "{}" добавлено'
str_human_delete_tree = '{} и его(её) потомки удалены из дерева {}'
str_human_input_tree = '{} добавлен(-а) в дерево {}'
str_human_update = 'Информация о человеке {} обновлена'
str_user_update = 'Информация о пользователе @{} обновлена'
str_user_delete = 'Аккаунт пользователя @{} удален'
str_user_input = 'Аккаунт @{} успешно зарегестрирован!'
str_user_accept_tree = 'Пользователь @{} допущен к дереву "{}"'
str_user_dontaccept_tree = 'Доступ @{} к дереву "{}" прекращен'

li_tree_with_image = '<li><div class="block_tree"><div class="around_photo_tree"><div class="photo_tree"><img class="personPhoto" src="{}"></div></div><div class="a_tree"><a href="{}">{}</a></div></div>'
li_tree = '<li><div class="block_tree"><div class="a_tree"><a class="without_image" href="{}">{}</a></div></div>'
li_breadcrumb = '<li class="breadcrumb-item"><a href="{}">{}</a></li>'
