# Generated by Django 3.0.10 on 2021-04-03 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 0, 9, 108856), verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='NumberChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Количество изменений')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='mainapp.Tree', verbose_name='Дерево')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
