# Generated by Django 3.1.3 on 2020-12-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201202_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='people',
        ),
        migrations.AlterField(
            model_name='human',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tree', verbose_name='Дерево'),
        ),
    ]
