# Generated by Django 3.1.3 on 2020-12-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20201205_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_children', to='mainapp.human', verbose_name='Родитель'),
        ),
        migrations.RemoveField(
            model_name='tree',
            name='user',
        ),
        migrations.AddField(
            model_name='tree',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
