# Generated by Django 3.1.3 on 2020-12-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tree_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='creator',
        ),
    ]
