# Generated by Django 3.1.3 on 2020-12-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20201207_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='creator',
        ),
    ]
