# Generated by Django 3.1.3 on 2020-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20201208_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
